### ISSUE TITLE
Add the ability to edit your data structure (following the point'n'click feature)

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/detective.io#643]
Maybe you've already did it but I can't find where to go to edit my data structure.

I think we should have a "adit data structure" button in the "edit" part of the data structure.

**Comment by n-kb** [comment]
Quand je mod la data structure (ajout d'un model et d'une rel), et que je reviens sur le topic, l'API renvoit alternativement le nouveau data structure et l'ancien. Y'a pas un moyen de flusher le cache du topic après une mod?

**Comment by Pirhoo** [comment]
Il devrait virer le cache en fait. Je regarde.
