### ISSUE TITLE
ontology creator: I can't add the "date" field

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/detective.io#668]
I really don't undersand, I chose the template body count, wanted to check if event has a date field (as in my csv) and that's what I obtain:

![capture d ecran 2014-12-18 a 17 37 44](https://cloud.githubusercontent.com/assets/2103603/5491872/dd3ea306-86dc-11e4-984f-3162beae1daf.png)

**Comment by annelisebouyer** [comment]
I added the verbose name in the topic skeleton but still have the same problem:
http://staging.detective.io/admin/detective/topicskeleton/1/

**Comment by Pirhoo** [comment]
It's probably be due to some cache...
