### ISSUE TITLE
Edit your data structure: When i change the **reverse name** of a relationship, an error occurs

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/detective.io#673]
For instance here http://staging.detective.io/annelise/ta-custom/country/190000/, I changed the reverse name of the relationship from "hosts" to "hosts a company".
Everything looks fine but after 30sec on this page, I see an error message.

![capture d ecran 2015-01-23 a 17 56 11](https://cloud.githubusercontent.com/assets/2103603/5878736/774e9150-a329-11e4-901c-bf7e98af159c.png)
![capture d ecran 2015-01-23 a 17 56 02](https://cloud.githubusercontent.com/assets/2103603/5878737/77517b40-a329-11e4-98da-15abf163920c.png)

**Comment by Pirhoo** [comment]
The `verbose_name` of reverse relationship is **NOT** a `verbose_name`, its just a name (Django does not support verbose_name for such field). We should disable renaming for such field.
