### ISSUE TITLE
Unable to create a long-text field inside a new relation ship

### ISSUE THREAD

**Issue by julesbonnard** [jplusplus/detective.io#674]
When creating a new data collection, you can't add a long-text field for a relationship between two data-models. The field just disappear then, you get an error if you retry with the same name...

![capture d ecran 2015-01-26 a 15 53 59](https://cloud.githubusercontent.com/assets/4705174/5901512/5688683c-a573-11e4-807b-cce8e8e76ecb.png)

**Comment by annelisebouyer** [comment]
Thanks for noticed it Jules, indeed it's a bug and I reproduced it. We will fix it soon!

**Comment by annelisebouyer** [comment]
it works when I create a data structure, and when I fill the field everything is stored.
But in the "see details", the long text field is displayed empty
http://staging.detective.io/annelise/my-company-ans-employees/company/190292/

![capture d ecran 2015-02-02 a 11 45 04](https://cloud.githubusercontent.com/assets/2103603/5999328/199540fe-aad1-11e4-9b0f-a8fc2fb32b71.png)
![capture d ecran 2015-02-02 a 11 44 54](https://cloud.githubusercontent.com/assets/2103603/5999329/199e3a10-aad1-11e4-9100-0b0e6699c481.png)

**Comment by Pirhoo** [comment]
I think it's an other issue :)

**Comment by annelisebouyer** [comment]
Ok I create a new ticket then!
