### ISSUE TITLE
When I change the name of a relationship, it's not taken into account

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/detective.io#675]
This time I change the "name" of a relationship, not the "reverse name".
I don't have any error but my change is not taken into account

ex here:http://staging.detective.io/annelise/my-company-ans-employees/person/190290/

I replaced Person "works" Company by Person "works at" Company. But after validation, I still see "works".
![capture d ecran 2015-02-02 a 11 50 46](https://cloud.githubusercontent.com/assets/2103603/5999419/fb40c8c0-aad1-11e4-8575-9b522c46cd69.png)
![capture d ecran 2015-02-02 a 11 50 29](https://cloud.githubusercontent.com/assets/2103603/5999420/fb498a1e-aad1-11e4-8e71-706629bbbdb0.png)

**Comment by annelisebouyer** [comment]
I still have this problem but it seems to work sometimes. For me it looks like the previous issue we had in changing the data structure, and restart the server.

**Comment by Pirhoo** [comment]
Do you reload the page ?

**Comment by annelisebouyer** [comment]
yes sure and clear the cache
