### ISSUE TITLE
Some data types don't appear in "edit data structure"

### ISSUE THREAD

**Issue by n-kb** [jplusplus/detective.io#679]
Quand j'édite la structure de données, je choisi "edit data model". Certains champs n'apparaissent pas (apparemment, les dates). Tous les champs sont set sur "short text", même ceux qui devraient être "long text".

Example here:

![screenshot from 2015-02-12 18 43 10](https://cloud.githubusercontent.com/assets/864677/6173288/08b46698-b2e7-11e4-92bc-2c2fa4c9c0be.png)

Alors que les company ont bien un champ "Founded (date)": https://www.detective.io/nkb/immoshark24/contribute/?type=company&id=74052

**Comment by annelisebouyer** [comment]
De mon côté sur ce topic par exemple je n'ai pas reproduit ce bug https://www.detective.io/somo/think-tanks/settings/structure/

Mais je n'ai aucun data model comprenant de date, il semblerait que le pb ne vienne que de date
