### ISSUE TITLE
Mixed content issue with gravatar

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/detective.io#686]
I don't know if it can cause a lot of bugs but I spotted that I have some mixed content warning dues to my gravatar pic (http).

![capture d ecran 2015-02-16 a 16 17 29](https://cloud.githubusercontent.com/assets/2103603/6214309/c54fa246-b5f7-11e4-92c9-b4596e65e6f6.png)

**Comment by Pirhoo** [comment]
No it can't cause any bug, just a warning.
