### ISSUE TITLE
Redirects

### ISSUE THREAD

**Issue by n-kb** [jplusplus/detective.io#699]
Redirect 
1. www.detective.io/detective/the-migrants-files/ to http://themigrantsfiles.com/
1. http://detective.io/detective/belarus-networks/ to http://jplusplus.github.io/belarus-networks/

**Comment by n-kb** [comment]
the redirect from detective.io to detective.io/tour doesn't work anymore.

**Comment by pirhoo** [comment]
This is an other issue but it's already fixed.

**Comment by n-kb** [comment]
damn you're fast! :rabbit2:
